CREATE TABLE TBL_CHAT
(
    CHAT_NO NUMBER auto_increment,
    SENDER VARCHAR2(260) NOT NULL,
    RECEIVER VARCHAR2(260) NOT NULL,
    CHAT_CONTENT VARCHAR2(10000) NOT NULL,
    CHAR_REGDATE DATETIME DEFAULT SYSDATE NOT NULL,
    PRIMARY KEY(CHAT_NO)
);