CREATE TABLE TBL_GONGJI
(
    GONGJI_NO NUMBER auto_increment,
    SENDER VARCHAR2(260) NOT NULL,
    RECEIVER VARCHAR2(260) NOT NULL,
    GONGJI_CONTENT VARCHAR2(10000) NOT NULL,
    PRIMARY KEY(GONGJI_NO)
);